INSERT INTO attractions(name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES
  ('Fira to Oia Hike',
    'Experience the stunning beauty of Santorini by hiking from Fira to Oia, passing through beautiful villages with breathtaking views of the Aegean Sea.',
    36.418808,
    25.430517,
    'Walking',
    4.8,
    0,
    240,
    true,
    'https://www.viator.com/tours/Santorini/Santorini-Caldera-Hike/d959-6357P39',
    '{"https://s27363.pcdn.co/wp-content/uploads/2019/05/Trail-to-the-Church.jpg.optimal.jpg", "https://media.tacdn.com/media/attractions-splice-spp-674x446/0b/39/b1/48.jpg", "https://tripanthropologist.com/wp-content/uploads/2019/08/fira_walk6-e1619258754244.jpg"}',
    'Santorini',
    'Greece'),

  ('Amoudi Bay',
    'Savor fresh seafood at charming tavernas, take a dip in the clear waters, or admire the beautiful sunsets at this picturesque bay below Oia.',
    36.461748,
    25.375495,
    'Dining',
    4.6,
    0,
    120,
    true,
    'https://www.viator.com/tours/Santorini/Santorini-Half-Day-Small-Group-and-Private-Tour/d959-6357P63',
    '{"https://pinayflyinghigh.com/wp-content/uploads/2016/07/Santorini-Greece-PinayFlyingHigh.com-162.jpg", "https://media-cdn.tripadvisor.com/media/photo-s/0c/d2/07/63/photo1jpg.jpg"}',
    'Santorini',
    'Greece'),

  ('Akrotiri Archaeological Site',
    'Explore the ancient Minoan settlement that was buried by volcanic ash during the Theran eruption around 1627 BCE.',
    36.351626,
    25.400577,
    'Cultural',
    4.5,
    12,
    120,
    false,
    'https://www.viator.com/tours/Santorini/Ancient-Akrotiri-and-Santorini-Winery-Tour/d959-6357WINERY',
    '{"https://www.ontheluce.com/wp-content/uploads/2015/11/akrotiri-santorini-greece-pompeii.jpg"}',
    'Santorini',
    'Greece'),

  ('Perissa Black Sand Beach',
    'Lounge on the unique black sand beach of Perissa, one of the largest beaches in Santorini, and enjoy water sports or a variety of beach bars and restaurants.',
    36.351430,
    25.471926,
    'Sightsee',
    4.3,
    0,
    180,
    false,
    'https://www.viator.com/tours/Santorini/Santorini-Beach-Day-With-Lunch/d959-6357P66',
    '{"https://images.santorini-view.com/ccd494f2_76a6_4baa_a1de_712c667bf988.limghandler.jpg?i=aT0lMmZ1cGxvYWRlZGZpbGVzJTJmMjAyMiUyZjAxJTJmMTIlMmZjY2Q0OTRmMi03NmE2LTRiYWEtYTFkZS03MTJjNjY3YmY5ODguanBlZyZ3PTcyMCZoPTU0MCZzdD10cnVlJmJnPTE2Nzc3MjE1JmNyPXRydWUmYXQ9NA%3D%3D"}',
    'Santorini',
    'Greece'),

  ('Pyrgos Village',
    'Experience the traditional life in the charming village of Pyrgos, the highest point of Santorini, offering panoramic views of the entire island.',
    36.383038,
    25.447758,
    'Walking',
    4.6,
    0,
    120,
    true,
    'https://www.viator.com/tours/Santorini/Private-Custom-Santorini-Tour/d959-6357P64',
    '{"https://greecetravelideas.com/wp-content/uploads/2023/01/Pyrgos-santorini-min.jpg", "https://arzotravels.com/wp-content/uploads/2021/02/what-to-do-in-Pyrgos-in-Santorini-Greece-with-Arzo-Travels.jpg", "https://www.demetercavehouse.com/wp-content/uploads/2019/03/Penelopes-Outside-Home-Cooked-Food-Pyrgos.jpg"}',
    'Santorini',
    'Greece'),

  ('Santo Wines Winery',
    'Enjoy wine tasting while admiring stunning views of the caldera and the Aegean Sea at one of Santorini’s most famous wineries.',
    36.372975,
    25.426802,
    'Tasting',
    4.5,
    25,
    90,
    false,
    'https://www.viator.com/tours/Santorini/Santorini-Wine-Tasting-and-Winery-Tour/d959-6357P65',
    '{"https://santo-line.com/wp-content/uploads/2017/12/wine-tasting3.jpg", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJ16TNWLNmqhHasqiXvZFsNw9Y3IccE8HhLfVlEmS0ywIBGQtdJx6DDXY8JrI15PuhTew&usqp=CAU"}',
    'Santorini',
    'Greece'),

  ('Ancient Thera',
    'Visit the ruins of this ancient city located on a ridge of the steep, 360 m high Messavouno mountain on the Greek island of Santorini.',
    36.359294,
    25.474613,
    'Cultural',
    4.4,
    4,
    90,
    false,
    'https://www.viator.com/tours/Santorini/Santorini-Full-Day-Sightseeing-Tour/d959-6357P67',
    '{"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/c5/fc/d3/a-king-s-view.jpg?w=1200&h=-1&s=1"}',
    'Santorini',
    'Greece'),

  ('Red Beach',
    'Relax on the unique red sand beach, one of the most scenic and interesting beaches on the island.',
    36.351658,
    25.397032,
    'Sightsee',
    4.2,
    0,
    90,
    false,
    'https://www.viator.com/tours/Santorini/Santorini-Island-Day-Trip/d959-6357P68',
    '{"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/a7/bf/3a/red-beach.jpg?w=1200&h=1200&s=1"}',
    'Santorini',
    'Greece'),

  ('Santorini Volcano and Hot Springs',
    'Experience a boat tour to the active volcano of Santorini, explore the island and have a dip in the hot springs.',
    36.401726,
    25.395939,
    'Luxury',
    4.5,
    20,
    180,
    false,
    'https://www.viator.com/tours/Santorini/Volcano-and-Hot-Springs-Boat-Tour/d959-6357P70',
    '{"https://s3.amazonaws.com/tourlandish/mircobrands-content/image/f067a017a3db86bb2cc2daeb2b3bb4a4-Santorini%20-%20Volcano.jpg"}',
    'Santorini',
    'Greece');

INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES 
('Red Fort',
 'Explore the 17th century historic fort which served as the main residence of the Mughal emperors.',
 28.6561592,
 77.2410203,
 'Cultural',
 4.4,
 10,
 120,
 false,
 'https://www.viator.com/tours/New-Delhi/Private-Full-Day-Tour-of-Old-and-New-Delhi/d804-5524DEL',
 '{"https://cdn.britannica.com/84/124684-004-07547A0D/Red-Fort-Old-Delhi-India.jpg"}',
 'New Delhi',
 'India'),

('Qutub Minar',
 'Visit the tallest minaret in India, a UNESCO World Heritage Site.',
 28.5244281,
 77.1854559,
 'Cultural',
 4.5,
 5,
 120,
 false,
 'https://www.viator.com/tours/New-Delhi/Private-Tour-Delhi-City-Tour-of-Qutub-Minar-and-Dilli-Haat/d804-5524QUTUB',
 '{"https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Qutub_Minar_Inscriptions_2022.jpg/220px-Qutub_Minar_Inscriptions_2022.jpg"}',
 'New Delhi',
 'India'),

('India Gate',
 'Visit this iconic monument built in memory of the Indian soldiers who lost their lives in World War I.',
 28.6129126,
 77.2295097,
 'Sightsee',
 4.6,
 0,
 60,
 false,
 'https://www.viator.com/tours/New-Delhi/Private-Delhi-City-Driver-with-Air-Conditioned-Car-for-your-Disposal-8-Hours/d804-5832P119',
 '{"https://www.historyhit.com/app/uploads/fly-images/5152849/India-Gate-788x537.gif?x87969"}',
 'New Delhi',
 'India'),

('Humayun Tomb',
 'Explore this stunning example of Mughal architecture, also a UNESCO World Heritage Site.',
 28.5932828,
 77.2507496,
 'Cultural',
 4.5,
 10,
 120,
 true,
 'https://www.viator.com/tours/New-Delhi/Private-Tour-of-Delhis-City-Monuments-including-entrance-to-the-tomb-of-Humayun/d804-5832P170',
 '{"https://upload.wikimedia.org/wikipedia/commons/c/c5/Humayun%27s_Tomb%2C_Delhi%2C_India_2019.jpg", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQp7fptRX18MaZzmCiQhBeErwQ_epCPYVXv94FKkvmCSEhENlOKwH2GrxfyjBa_Y2nXFJo&usqp=CAU", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2UZJSIif58_LngDXw4RxJjTeD5Sc2Bk6VoQ&usqp=CAU"}',
 'New Delhi',
 'India'),

('Lotus Temple',
 'Visit this unique lotus-shaped marble temple, a Baháʼí House of Worship notable for its flowerlike shape.',
 28.553492,
 77.2588264,
 'Sightsee',
 4.6,
 0,
 60,
 false,
 'https://www.viator.com/tours/New-Delhi/Private-Delhi-City-Driver-with-Air-Conditioned-Car-for-your-Disposal-8-Hours/d804-5832P119',
 '{"https://cdn.britannica.com/67/156667-050-62285333/Lotus-Temple-New-Delhi-India.jpg"}',
 'New Delhi',
 'India'),

('Swaminarayan Akshardham',
 'Explore this stunning spiritual-cultural campus dedicated to devotion, learning and harmony.',
 28.612673,
 77.277261,
 'Cultural',
 4.6,
 0,
 180,
 false,
 'https://www.viator.com/tours/New-Delhi/Private-Tour-Delhi-in-One-Day/d804-5693DELHIDAY',
 '{"https://akshardham.com/newdelhi/wp-content/uploads/2015/06/akshardham_facts_and_figure_banner.jpg"}',
 'New Delhi',
 'India'),

('Jama Masjid',
 'Visit one of the largest mosques in India and a classic example of Mughal architecture.',
 28.6505948,
 77.2303282,
 'Cultural',
 4.4,
 0,
 90,
 false,
 'https://www.viator.com/tours/New-Delhi/Old-Delhi-Group-Tour/d804-5693DELHITOUR',
 '{"https://upload.wikimedia.org/wikipedia/commons/a/a4/Jama_Masjid_-_In_the_Noon.jpg"}',
 'New Delhi',
 'India'),

('Lodi Gardens',
 'Take a leisurely stroll or enjoy a picnic in this city park situated in New Delhi.',
 28.593314,
 77.219489,
 'Sightsee',
 4.5,
 0,
 120,
 false,
 'https://www.viator.com/tours/New-Delhi/Private-Custom-Tour-Delhi-in-One-Day/d804-5693P45',
 '{"https://www.historyhit.com/app/uploads/fly-images/5153319/Lodhi-Garden-788x537.jpg?x87969"}',
 'New Delhi',
 'India'),

('Raj Ghat',
 'Visit the memorial dedicated to Mahatma Gandhi, marking the spot of his cremation.',
 28.6415,
 77.2483,
 'Cultural',
 4.5,
 0,
 60,
 false,
 'https://www.viator.com/tours/New-Delhi/Private-Tour-Delhi-in-One-Day/d804-5693DELHIDAY',
 '{"https://cdn.getyourguide.com/img/tour/5da9647217413.jpeg/97.jpg"}',
 'New Delhi',
 'India'),

('National Gandhi Museum',
 'Explore the museum dedicated to the life of Mahatma Gandhi, displaying his personal items and letters.',
 28.6415,
 77.2483,
 'Cultural',
 4.5,
 0,
 120,
 false,
 'https://www.viator.com/tours/New-Delhi/Private-Delhi-City-Tour-Including-New-Delhi-and-Old-Delhi/d804-13152P50',
 '{"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/14/86/f7/national-gandhi-museum.jpg?w=1200&h=1200&s=1"}',
 'New Delhi',
 'India');
