INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES 
('Statue of Liberty and Ellis Island Guided Tour',
 'Enjoy a guided tour of the Statue of Liberty and Ellis Island with an expert guide and without the wait. You’ll have early reserve line access to the Statue of Liberty Ferry and then visit the new Statue of Liberty Museum.',
 40.6892, 
 -74.0445, 
 'Cultural', 
 4.8, 
 57, 
 240, 
 true, 
 'https://www.viator.com/tours/New-York-City/Statue-of-Liberty-and-Ellis-Island-Guided-Tour/d687-5250P1',
 'https://cdn.britannica.com/82/183382-050-D832EC3A/Detail-head-crown-Statue-of-Liberty-New.jpg', 
 'New York', 
 'USA'),

('Central Park Bike Rental',
 'Discover Central Park from its early origins to the present day with Central Park Pedicabs. Your friendly tour guide will customize your Pedicab experience, stopping at your favorite spots.',
 40.7829, 
 -73.9654, 
 'Sightsee', 
 4.5, 
 15, 
 120, 
 false, 
 'https://www.viator.com/tours/New-York-City/Central-Park-Bike-Rental/d687-5557P13',
 'https://media.tacdn.com/media/attractions-splice-spp-674x446/06/75/c4/bb.jpg',
 'New York',
 'USA'),

('9/11 Memorial & Museum Admission Ticket',
 'Pay your respects to the victims of the 9/11 attacks at the 9/11 Memorial & Museum. Journey through the history of the World Trade Center and learn about the stories of the people involved.',
 40.7115, 
 -74.0134,
 'Cultural',
 4.7,
 28,
 180,
 false,
 'https://www.viator.com/tours/New-York-City/9-11-Memorial-and-Museum-Admission-Ticket/d687-5250P23',
 'https://assets.simpleviewinc.com/simpleview/image/upload/crm/newyorkstate/9-11-memorial-03-marley-white_08304459-fd51-e9bc-1df612407cbe64fb.jpg',
 'New York',
 'USA'),

('New York in One Day Guided Sightseeing Tour',
 'See as much as you can in fast-moving New York on this comprehensive 5-hour coach sightseeing tour of the Big Apple’s top attractions.',
 40.7128, 
 -74.0060, 
 'Sightsee', 
 4.6, 
 89, 
 300, 
 false, 
 'https://www.viator.com/tours/New-York-City/New-York-in-One-Day-Guided-Sightseeing-Tour/d687-7081P4',
 ARRAY['https://upload.wikimedia.org/wikipedia/commons/4/47/New_york_times_square-terabass.jpg", "https://cdn.contexttravel.com/image/upload/w_1500,q_60/v1571947279/blog/36%20Hours%20in%20NYC/NewYorkStreets.jpg"],
 'New York',
 'USA'),

('Empire State Building General & Skip-the-Line Tickets',
 'Soak up the panoramic views of NYC from the Empire State Building Observatory—iconic views that are not to be missed.',
 40.748817, 
 -73.985428,
 'Sightsee',
 4.5,
 45.73,
 120,
 true,
 'https://www.viator.com/tours/New-York-City/Empire-State-Building-General-and-Skip-the-Line-Tickets/d687-2194EMPIRE',
 'https://worldadventurists.com/wp-content/uploads/2018/05/empirestate05.jpg',
 'New York',
 'USA'),

('Top of the Rock Observation Deck, New York Ticket',
 'Admire New York City’s top sights from the skies with this exhilarating helicopter tour.',
 40.7590, 
 -73.9793,
 'Sightsee',
 4.6,
 41,
 60,
 false,
 'https://www.viator.com/tours/New-York-City/Top-of-the-Rock-Observation-Deck-New-York/d687-3784TOPROCK',
 'https://images.ctfassets.net/s2zqt2a15zcl/3QzQDDZqI0OQWuW4oKyEQe/b142c2a6f647e0f96a98bbc6b653040a/cover-post-open-door-helicopter.jpg',
 'New York',
 'USA'),

('Manhattan Sky Tour: New York Helicopter Flight',
 'Admire New York City’s top sights from the skies with this exhilarating helicopter tour.',
 40.7829, 
 -73.9654,
 'Luxury',
 4.7,
 209,
 15,
 true,
 'https://www.viator.com/tours/New-York-City/Manhattan-Sky-Tour-New-York-Helicopter-Flight/d687-5024HELI',
 'https://media.tacdn.com/media/attractions-splice-spp-674x446/06/6b/8f/3a.jpg',
 'New York',
 'USA'),

('New York CityPASS',
 'Gain admission to The Metropolitan Museum of Art, The Empire State Building Experience, The American Museum of Natural History, and much more.',
 40.7128, 
 -74.0060,
 'Cultural',
 4.6,
 136,
 1080,
 true,
 'https://www.viator.com/tours/New-York-City/New-York-CityPASS/d687-2640NYC',
 'https://www.metmuseum.org/-/media/images/visit/met-fifth-avenue/fifthave_teaser.jpg?sc_lang=en"',
 'New York',
 'USA'),

('Madame Tussauds New York Admission Ticket',
 'Experience the magic of Broadway like never before at Madame Tussauds New York.',
 40.7564,
 -73.9889,
 'Sightsee',
 4.1,
 32.51,
 120,
 false,
 'https://www.viator.com/en-CA/tours/London/Skip-the-Line-Madame-Tussauds-London/d737-2798TUSSAUDS',
 'https://assets.simpleviewinc.com/simpleview/image/upload/crm/newyorkstate/Marilyn-Monroe_B1706CCC-AE33-B2FB-23B9CA7F4420EF8C-b1706c41e461b06_b1706d20-e646-e9b5-b442bdcbcac4aba0.jpg',
 'New York',
 'USA');

 INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES 
('Madison Square Garden All Access Tour',
 'Explore hallowed grounds considered the world’s most famous arena. On the Madison Square Garden All Access Tour, you will uncover the secrets of iconic moments in sports, music, and entertainment history.',
 40.7505, 
 -73.9934, 
 'Sightsee', 
 4.5, 
 35, 
 75, 
 false, 
 'https://www.viator.com/tours/New-York-City/Madison-Square-Garden-All-Access-Tour/d687-6341P4',
 'https://img.msg.com/wp-content/uploads/2021/02/BillyJoel_071818_1902_RT-1.jpg',
 'New York',
 'USA'),

('The High Line Park',
 'Stroll through the beautiful High Line, a 1.45-mile-long elevated park built on a former New York Central Railroad.',
 40.748817, 
 -74.0048,
 'Budget',
 4.8,
 0,
 120,
 false,
 'https://www.thehighline.org/',
 'https://media.cntraveler.com/photos/5a83590826924e3c324ef342/16:9/w_2560,c_limit/The-Highline_2018_1407-High-Line-At-The-Rail-Yards---Photo-By-Iwan-Baan_1411215715.jpg',
 'New York',
 'USA'),

('Little Italy Food Tour in New York',
 'Discover the best pizza slices in town in the neighborhood known for its rich culture and tasty food.',
 40.7196, 
 -73.9976,
 'Tasting',
 4.7,
 50,
 180,
 false,
 'https://www.viator.com/tours/New-York-City/Little-Italy-Food-Tour-in-New-York/d687-5683FOODTOUR',
 'https://media-cdn.tripadvisor.com/media/photo-s/06/14/b6/17/little-italy-pizza.jpg',
 'New York',
 'USA'),

('Hudson Yards Vessel Experience',
 'Discover a new kind of landmark: Vessel, the centerpiece of Hudson Yards. It’s an interactive structure built to be climbed, and the experience is all about the journey.',
 40.7536, 
 -74.0005,
 'Sightsee',
 4.3,
 10,
 60,
 true,
 'https://www.hudsonyardsnewyork.com/discover/vessel',
 'https://nypost.com/wp-content/uploads/sites/2/2019/03/hudson-yards-vessel-main-1a.jpg',
 'New York',
 'USA'),

('Bronx Zoo Admission Ticket',
 'Spend the day at the Bronx Zoo and see your favorite animals up close.',
 40.8506, 
 -73.8766,
 'Sightsee',
 4.6,
 36.95,
 240,
 false,
 'https://www.viator.com/tours/New-York-City/Bronx-Zoo-Admission-Ticket/d687-5831BRONXZOO',
 'https://travel.usnews.com/images/Bronx_Zoo_sign.jpg',
 'New York',
 'USA'),

('Coney Island Excursion',
 'Experience the thrill of the amusement park, visit the New York Aquarium, or relax on the beach. Coney Island has something for everyone.',
 40.5755, 
 -73.9707,
 'Budget',
 4.5,
 0,
 240,
 true,
 'https://coneyislandfunguide.com/',
 'https://media.timeout.com/images/105763396/image.jpg',
 'New York',
 'USA'),

('New York TV and Movie Sites Tour',
 'Visit more than 60 filming locations from famous TV shows and movies on this comprehensive tour of Manhattan.',
 40.7128, 
 -74.0060,
 'Sightsee',
 4.5,
 51,
 180,
 false,
 'https://www.viator.com/tours/New-York-City/New-York-TV-and-Movie-Sites-Tour/d687-2218TVMOVIE',
 'https://a.storyblok.com/f/112937/569x464/48e2a6cd85/top_new_york_film_sites_you_have_to_visit_web.jpg',
 'New York',
 'USA'),

('New York Botanical Garden Admission',
 'Explore 250 acres of stunning garden landscapes and the world-renowned Enid A. Haupt Conservatory.',
 40.8623, 
 -73.8773,
 'Budget',
 4.7,
 28,
 180,
 true,
 'https://www.viator.com/tours/New-York-City/New-York-Botanical-Garden-Admission/d687-5841NYBG',
 'https://imageio.forbes.com/blogs-images/micheleherrmann/files/2019/02/NYBGTheOrchidShowSingapore-Arches-MCOB0807-1200x800.jpg?format=jpg&width=1200',
 'New York',
 'USA'),

('Brooklyn Heights and DUMBO Walking Tour',
 'Explore the elegant brownstones and historic residences of Brooklyn Heights and experience the modern, artsy vibe of DUMBO.',
 40.7027, 
 -73.9913,
 'Walking',
 4.7,
 35,
 180,
 false,
 'https://www.viator.com/tours/New-York-City/Brooklyn-Heights-and-DUMBO-Walking-Tour/d687-5250BROOKLYN',
 'https://www.takewalks.com/blog/wp-content/uploads/2012/07/Cranberry-St-1024x768.jpg',
 'New York',
 'USA'),

('The Loeb Boathouse Dining Experience',
 'Enjoy lunch, brunch, or dinner at The Loeb Boathouse in Central Park. Offering stunning views of the lake and Manhattan skyline.',
 40.7742, 
 -73.9680,
 'Dining',
 4.6,
 75,
 120,
 false,
 'https://www.opentable.com/the-loeb-boathouse-at-central-park',
 'https://centralparkbikerental.nyc/content/uploads/attractions/5831d0498e7fa_loeb_boathouse_2.jpg',
 'New York',
 'USA');

INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES 
('Golden Gate Bridge',
 'Take a walk on this iconic suspension bridge, one of the most internationally recognized symbols of San Francisco.',
 37.8199, 
 -122.4783,
 'Sightsee',
 4.8,
 0,
 60,
 false,
 'https://www.sftravel.com/article/8-things-to-do-near-golden-gate-bridge',
 ARRAY["https://www.goldengate.org/assets/1/6/bridge.jpg", "https://i.natgeofe.com/n/024969fc-c29a-4f2c-b51c-8604c13df722/golden-gate-painter-590.jpg"],
 'San Francisco',
 'USA'),

('Alcatraz Island',
 'Visit the notorious former prison offering stunning views of the San Francisco Bay.',
 37.8267,
 -122.4230,
 'Cultural',
 4.7,
 39.9,
 180,
 false,
 'https://www.viator.com/tours/San-Francisco/Alcatraz-and-San-Francisco-City-Tour/d651-2660SFALCATRAZ',
 'https://www.nps.gov/alca/planyourvisit/images/Alcatraz_8.jpg?maxwidth=1300&maxheight=1300&autorotate=false',
 'San Francisco',
 'USA'),

('Fishermans Wharf',
 'Explore this lively neighborhood, known for the Ghirardelli Square, delicious seafood, spectacular sights and unique shopping.',
 37.8080,
 -122.4177,
 'Budget',
 4.5,
 0,
 120,
 true,
 'https://www.expedia.co.uk/San-Francisco-Fishermans-Wharf.dx800128',
 ARRAY["https://www.omnihotels.com/-/media/images/globals/cityshots/san-francisco-fishermans-wharf-istock-52826370.jpg?h=660&la=en&w=1170", "https://a.travel-assets.com/findyours-php/viewfinder/images/res70/22000/22337-Pier-39.jpg"],
 'San Francisco',
 'USA'),

('Union Square',
 'Shop, dine, or just hang out in this vibrant neighborhood, the heartbeat of San Francisco.',
 37.7879,
 -122.4074,
 'Walking',
 4.5,
 0,
 120,
 false,
 'https://www.expedia.ca/San-Francisco-Union-Square.dx800129',
 ARRAY["https://www.tripsavvy.com/thmb/ml2kHTdsDj6Zqr2PaCX3tarP-hs=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-109287627-5b66fb4f46e0fb0050fabc66.jpg", "https://a.travel-assets.com/findyours-php/viewfinder/images/res70/173000/173736-Union-Square.jpg",
 "https://unionsquareshop.com/assets/img/carousel/01.jpg"],
 'San Francisco',
 'USA'),

('Chinatown',
 'Walk through the oldest Chinatown in North America and the largest Chinese enclave outside Asia, rich in history and bustling with energy.',
 37.7941,
 -122.4078,
 'Walking',
 4.4,
 0,
 120,
 true,
 'https://www.tripadvisor.ca/Attractions-g60713-Activities-zfn7222615-San_Francisco_California.html',
 ARRAY["https://media.timeout.com/images/102875459/image.jpg", "https://upload.wikimedia.org/wikipedia/commons/7/75/San_Francisco_China_Town_MC.jpg", "https://img.theculturetrip.com/wp-content/uploads/2019/02/e72fcp.jpg", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/c1/dc/5e/chinatown.jpg?w=500&h=-1&s=1"],
 'San Francisco',
 'USA'),

('Palace of Fine Arts',
 'Admire the monumental structure originally constructed for the 1915 Panama-Pacific Exposition. Relax in the peaceful garden setting or walk around the lagoon.',
 37.8029,
 -122.4487,
 'Cultural',
 4.8,
 0,
 60,
 true,
 'https://www.viator.com/tours/San-Francisco/Private-Luxury-Car-Tour-of-San-Francisco/d651-6548P2',
 ARRAY["https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Palace_of_Fine_Arts_%2816794p%29.jpg/1200px-Palace_of_Fine_Arts_%2816794p%29.jpg", "https://a.cdn-hotels.com/gdcs/production86/d861/5855df3c-b990-4888-8baf-94eeb2f7ea48.jpg", "https://live.staticflickr.com/1921/30569574997_78f698f28f_b.jpg"],
 'San Francisco',
 'USA'),

('Golden Gate Park',
 'Enjoy the vast green space with a variety of attractions, including the De Young Museum, San Francisco Botanical Garden, and Stow Lake.',
 37.7694,
 -122.4862,
 'Sightsee',
 4.8,
 0,
 180,
 false,
 'https://www.viator.com/tours/San-Francisco/Self-Guided-Bike-Tour-of-Golden-Gate-Park/d651-9215P1',
 'https://a.cdn-hotels.com/gdcs/production146/d1838/6e00c531-390b-4a91-8964-1c00198ceec9.jpg',
 'San Francisco',
 'USA'),

('Lombard Street',
 'Drive or walk down the most crooked street in the world with eight hairpin turns. Marvel at the steep, hilly street filled with beautiful Victorian mansions.',
 37.8021,
 -122.4186,
 'Sightsee',
 4.6,
 0,
 30,
 false,
 'https://www.sftravel.com/things-to-do/attractions/iconic-sf/lombard-street',
 ARRAY["https://www.sfmta.com/sites/default/files/imce-images/2019/lombard-street-san-fran_2.jpg", "https://s.hdnux.com/photos/01/31/30/42/23431335/5/1200x0.jpg"],
 'San Francisco',
 'USA'),

('Painted Ladies',
 'Explore the iconic row of Victorian houses at Alamo Square, one of the most photographed locations in San Francisco.',
 37.7763,
 -122.4348,
 'Sightsee',
 4.5,
 0,
 30,
 false,
 'https://www.sftravel.com/things-to-do/attractions/iconic-sf/painted-ladies',
 ARRAY["https://www.travelinusa.us/wp-content/uploads/sites/3/2017/11/Painted-Ladies-San-Francisco-01.jpg", "https://www.sftravel.com/sites/default/files/styles/hero/public/2022-10/painted-ladies-city-skyline-twilight.jpg.webp?itok=MVU3kPdc"],
 'San Francisco',
 'USA'),

('The Exploratorium',
 'Enjoy a playful, interactive science museum with exhibits that will engage both children and adults.',
 37.8009,
 -122.3986,
 'Cultural',
 4.6,
 29.95,
 180,
 false,
 'https://www.cntraveler.com/activities/san-francisco/exploratorium',
'https://www.exploratorium.edu/sites/default/files/2023-01/ExploAwardsDinner_050918_079-downsized-for-web.jpeg',
 'San Francisco',
 'USA');
