INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES 
('Promenade des Anglais',
 'Walk along the famous seafront avenue with the view of the Mediterranean on one side and a line of palm trees on the other.',
 43.6952,
 7.2706,
 'Walking',
 4.6,
 0,
 120,
 true,
 'https://www.hotel-locarno.com/en/blog/articles/the-most-beautiful-beaches-of-the-promenade-des-anglais-36589',
 '{"https://d2um6tst3jvq2w.cloudfront.net/cache/img/49fb9e32985a75a52ff77ed09b1a106b8de38ff6-49fb9e-450-300-crop.jpg?q=1647273710"}',
 'Nice',
 'France'),

('Castle Hill',
 'Climb the hill for a panoramic view of Nice and its vast coastline.',
 43.695870,
 7.281530,
 'Sightsee',
 4.6,
 0,
 90,
 false,
 'https://rivierabarcrawltours.com/castle-hill-nice-france/',
 '{"https://rivierabarcrawltours.com/wp-content/uploads/2020/01/Castle-Hill-Nice-France-cascade-river.jpg"}',
 'Nice',
 'France'),

('Old Town (Vieille Ville)',
 'Discover the narrow, winding streets filled with small shops, art galleries, and cafes.',
 43.6973,
 7.2800,
 'Cultural',
 4.5,
 0,
 120,
 true,
 'https://www.viator.com/tours/Nice/Best-of-Nice-Hour-Bike-Tour/d478-70038P13',
 '{"https://a.cdn-hotels.com/gdcs/production137/d367/3700ee9a-66ca-491b-8b7e-df8977f85008.jpg"}',
 'Nice',
 'France'),

('Cours Saleya Market',
 'Browse through this vibrant market full of fruits, vegetables, flowers, and local specialties.',
 43.6955,
 7.2770,
 'Tasting',
 4.7,
 0,
 120,
 false,
 'https://www.viator.com/tours/Nice/Food-Lovers-Tour-of-Nice-Local-Markets-and-Best-Shops/d478-70038P9',
 '{"https://www.bestofniceblog.com/wp-content/uploads/2012/03/Brocante-Mary-Payne-1-1-20101-300x225.jpg"}',
 'Nice',
 'France'),

('Place Massena',
 'Visit the city main square surrounded by beautiful red ochre buildings and a refreshing fountain.',
 43.6972,
 7.2702,
 'Walking',
 4.5,
 0,
 60,
 true,
 'https://www.viator.com/tours/Nice/Nice-City-Sightseeing-Small-Group-Tour/d478-70038P10',
 '{"https://rivierabarcrawltours.com/wp-content/uploads/2020/04/place-massena-apollo-1024x675-1.jpeg"}',
 'Nice',
 'France'),

('Nice Cathedral (Cathedrale Sainte-Reparate)',
 'Explore this stunning Baroque cathedral located in the old town of Nice.',
 43.6950,
 7.2773,
 'Cultural',
 4.5,
 0,
 60,
 false,
 'https://www.viator.com/tours/Nice/Historical-Center-Walking-Tour-of-Nice/d478-70038P11',
 '{"https://static.seetheworld.com/image_uploader/photos/38/original/sainte-reparate-cathedral-nice-nice-area-153.jpg"}',
 'Nice',
 'France'),

('Marc Chagall National Museum',
 'Visit the museum dedicated to the works of painter Marc Chagall.',
 43.7092,
 7.2774,
 'Cultural',
 4.6,
 10,
 120,
 true,
 'https://www.viator.com/tours/Nice/Private-Tour-of-the-Marc-Chagall-Museum-in-Nice/d478-7237P23',
 '{"https://pleinsud.art/media/pages/lieux/musee-national-marc-chagall/chagall-et-moi-les-50-ans-du-musee-national-marc-chagall/0f83a7e23a-1674478446/img_7934-musee-chagall-nice-1920_960px-22-recadree_0.jpg"}',
 'Nice',
 'France'),

('Phoenix Park (Parc Phoenix)',
 'Visit this large urban park with a zoo, botanical garden and an array of different species.',
 43.6671,
 7.2189,
 'Sightsee',
 4.4,
 5,
 180,
 false,
 'https://www.viator.com/tours/Nice/Nice-City-Tour-and-Old-town-Half-Day-from-Nice-Small-Group/d478-70038P18',
 '{"https://frenchriviera.travel/wp-content/uploads/2018/09/Parc-Phoenix1.jpg"}',
 'Nice',
 'France'),

('Russian Orthodox Cathedral',
 'Visit the largest Russian Orthodox cathedral outside Russia, with its striking onion-shaped domes.',
 43.7034,
 7.2663,
 'Cultural',
 4.5,
 10,
 90,
 true,
 'https://www.viator.com/tours/Nice/Nice-City-Tour-and-Old-town-Half-Day-from-Nice-Small-Group/d478-70038P18',
 '{"https://perfectlyprovence.co/wp-content/uploads/2020/11/Eglise-Russe.CRT-COTE-DAZUR-FRANCEPierre-BEHAR.jpg"}',
 'Nice',
 'France'),

('Matisse Museum',
 'Visit the museum dedicated to the life and work of French painter Henri Matisse.',
 43.7192,
 7.2768,
 'Cultural',
 4.4,
 10,
 120,
 false,
 'https://www.viator.com/tours/Nice/Private-Tour-of-the-Matisse-Museum-in-Nice/d478-7237P24',
 '{"https://www.irresistible-riviera.fr/images/decouvrir/musee-matisse/musee-matisse-nice-10-m.jpg"}',
 'Nice',
 'France');

INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES ('Compagnie des Bateaux Mouches Bastille Day Seine River Dinner Cruise',
 'Have a Champagne dinner cruise, taste a French traditional cooking, prepared on board by our own chef. Enjoy a 2h15 magic cruise with live music! At the end of the dinner, make yourself comfortable and watch the firework display from the upper-deck.',
 48.86401059999999,
2.3059374,
'Dining',
4.3,
195,
120,
false,
'http://www.partner.viator.com/en/13257/tours/Paris/Bastille-day-dinner-cruise/d479-23561P13?eap=prod-sRa7AtLuF4UkLYO6mKPY-13257&aid=vba13257en',
'{"https://media.tacdn.com/media/attractions-splice-spp-674x446/06/70/07/58.jpg"}',
'Paris',
'France'),

('Paris: Full-Day Customized Private Walking Tour with a Local',
'Discover the history and culture within Paris on this customized tour. Just let the guide know about your interests and all the legwork will be planned for you. Join a passionate, knowledgeable and engaging local as your guide around this immense city.',
48.85693,
2.3412,
'Walking',
3.0,
434,
420,
false,
'https://www.getyourguide.com/paris-l16/paris-full-day-customized-private-tour-t226705/?partner_id=B9IC1H4&psrc=partner_api&currency=EUR',
ARRAY['https://static01.nyt.com/images/2023/07/01/travel/22hours-paris-tjzf/22hours-paris-tjzf-superJumbo.jpg', 'https://www.cia-france.com/media/1804/paris-monument_1100x700.jpeg', 'https://images.squarespace-cdn.com/content/v1/58c35a0e579fb3281396b7f0/1628430130397-3J5N090EA4GH6891YZ5P/shangri+la+paris' ],
'Paris',
'France'),

('Paris Dark Side Walking Tour',
'Our Dark Paris private tour is the ideal way to unveil the most secret & mysterious legends of the City of Lights. From the Antic Latin Quarter to Notre Dame surroundings, and from the Marais to the Haunted Châtelet. It won’t leave you indifferent. Secure your spot now!Enjoy a private Paris Evening Tour with a Local Expert Guide.Explore the medieval heart of Paris, where each street corner hides stories to reveal.Decipher hidden symbols & gothic statues by the churches where dreadful stories happened. Discover back alleys where criminals & alchemists haunted for centuries.From the Middle Ages to the 1960s, unveil the darkness behind the Parisian nightlife.The iconic centre of Paris and Notre Dame cathedral will never look the same after this unique experience!',
48.86514500000001,
2.356986,
'Walking',
5.0,
124.5,
120,
true,
'http://www.partner.viator.com/en/13257/tours/Paris/Dark-Paris-Myths-and-Legends-Small-Group-Walking-Tour-10-max/d479-19551P49?eap=prod-fxUokaxbikskDHdLPsA3-13257&aid=vba13257en',
'{"https://www.ourescapeclause.com/wp-content/uploads/2019/12/shutterstock_1598542261-768x1024.jpg", "https://worldinparis.com/wp-content/uploads/2022/01/Place-du-Tertre-Night.jpg", "https://www.discoverwalks.com/blog/wp-content/uploads/2015/07/paris-at-night-big.jpg"}',
'Paris',
'France'),

('Luxury private day tour to Champagne from Paris',
'With this luxury day tour to Champagne, we make sure that you visit and taste only the best the region has to offer. We have crafted this trip with hand picked partners so you can have a perfect experience from start to finish. From the discovery of one of the world’s most prestigious Champagne producers, like Champagne Dom Pérignon or Champagne Ruinart, to the visit of a confidential winery making rare & haute couture champagnes to the passion of your guide who will share his knowledge about wine and Champagne, which is the result of a perfect blend between the land, the climate and century old craftsmanship, this is a perfect day around the world’s most illustrious drink, symbol of prestige and great achievements. Enjoy an exclusive gourmet lunch at a Michelin * restaurant, paired with wines. This tour includes hôtel pick up and drop off by air-conditioned black car or minivan and your private wine expert guide.',
48.8711057,
2.3694001,
'Luxury',
5.0,
1000,
660,
true,
'http://www.partner.viator.com/en/13257/tours/Paris/Luxury-private-day-tour-to-Champagne-from-Paris/d479-35428P6?eap=prod-xyxY1Y4tF3MsHDmXNout-13257&aid=vba13257en',
'{"https://i.pinimg.com/originals/65/00/ca/6500cabdbe20020144dc1ba44dc4aa77.jpg"}',
'Paris',
'France'),

('Eiffel Tower',
'The Eiffel Tower is a wrought-iron lattice tower and a global icon of France and one of the most recognizable structures in the world.',
48.8584,
2.2945,
'Sightsee',
4.8,
20.0,
120,
true,
'https://www.example.com/bookings/eiffel-tower',
'{"https://static.independent.co.uk/s3fs-public/thumbnails/image/2014/03/25/12/eiffel.jpg"}',
'Paris',
'France'),

('Louvre Museum',
'The Louvre Museum is the world''s largest art museum and a historic monument in Paris, France.',
48.8606,
2.3376,
'Cultural',
4.7,
18.0,
180,
true,
'https://www.louvre.fr/en',
'{"https://media.architecturaldigest.com/photos/5900cc370638dd3b70018b33/1:1/w_2066,h_2066,c_limit/Secrets%20of%20Louvre%201.jpg"}',
'Paris',
'France'),

('Notre-Dame Cathedral',
'Notre-Dame Cathedral is a medieval Catholic cathedral on the Île de la Cité in the fourth arrondissement of Paris, France.',
48.8530,
2.3499,
'Cultural',
4.6,
0.0,
60,
true,
'https://parisjetaime.com/eng/culture/tours-de-notre-dame-de-paris-p3540',
'{"https://upload.wikimedia.org/wikipedia/commons/f/f7/Notre-Dame_de_Paris%2C_4_October_2017.jpg"}',
'Paris',
'France');

INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES ('Longboard dancing course in Paris',
        'Discover the sport trend of the moment: longboard dancing in Paris with No Limit Coaching. Discover longboard dancing with an experienced instructor near the famous spot of the Saint Honoré market between the Parc de Rivoli and the Opera Garnier, in Paris. Longboard dancing is the urban sports activity of the moment. It is a mix of longboard and dance, accessible to all and can be practiced everywhere. No Limit Coaching offers you an introductory or advanced course in this practice during which you will learn to ride and evolve on the board in complete safety. Your instructor will adapt his course and his pedagogy to the level of each one so that everyone can take a maximum of pleasure and progress quickly. Besides the artistic and fun part, this practice also teaches you to trust yourself, to find your balance and to surpass yourself. Good sensations guaranteed!',
        48.866941,
        2.332153,
        'Budget',
        4.0,
        30,
        90,
        false,
        'https://alentour.adrenaline-hunter.com/en-GB/embedded-booking/activity/12134?_cid=603',
        ARRAY['https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2021/06/deb8db436cbe1872337d97e63249ed77.jpg', 'https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2021/06/69220febb15405264b3404dbd65feb65.jpg', 'https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2021/06/8cf5b7c0887cf878e9257c5dd8c14e03.jpg', 'https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2021/06/b5b6e03a76f0fd8eae509a23eca66700.jpg'],
        'Paris',
        'France');
INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES ('Guided Visit and Wine Tasting in a Royal Wine Cellar in Paris',
        'Visit a royal wine cellar in the heart of Paris: discover and learn about French wine in a fun and interactive experience!',
        48.8609185,
        2.3426596,
        'Tasting',
        4.5,
        35.0,
        60,
        false,
        'http://www.partner.viator.com/en/13257/tours/Paris/Guided-Visit-and-Wine-Tasting-in-a-Royal-Wine-Cellar-in-Paris/d479-23034P3?eap=prod-fxUokaxbikskDHdLPsA3-13257&aid=vba13257en',
        ARRAY['https://media.tacdn.com/media/attractions-splice-spp-674x446/07/75/a7/ea.jpg'],
        'Paris',
        'France');

INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES ('Luxury Paris, french fashion history walking tour',
        'We will walk in the luxury districts near Opera Garnier, Faubourg Saint Honoré street and Madeleine. During this experience you will discover the history of the most famous luxury fashion brands and learn how to read their collection today. Every brand has a DNA and follows it since the beginning. How? I will explain. We will enter a lot of first boutiques to discover the luxury universe from inside and see the newest collections. Do you know: How a fashion designer did change a women''s life? Why Coco Chanel is so famous today and how her men influenced her career? What Yves Saint Laurent hide from everybody? Who is Louis Vuitton and what''s his story? Why Hermès is so expensive and inaccessible today? What makes us buy and desire fashion brands? You''ll have the answers during our experience. It''s adapted for the "beginners" in fashion and people who want to know how the fashion industry lives.',
        48.8579759,
        2.361014699999999,
        'Walking',
        2.5,
        26.0,
        60,
        false,
        'http://www.partner.viator.com/en/13257/tours/Paris/Luxury-Paris-french-fashion-history-walking-tour/d479-123350P7?eap=prod-fxUokaxbikskDHdLPsA3-13257&aid=vba13257en',
        ARRAY['https://www.tripsavvy.com/thmb/iJHIhTxaf0e0I4dP0I8vIdYCWUk=/3936x2624/filters:no_upscale():max_bytes(150000):strip_icc()/TAM_2376-25f45c19d9cc4530929f941f6c0da811.jpg'],
        'Paris',
        'France');
INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES ('Bistro Parisien 3-Course-Lunch and Seine River Sightseeing Cruise',
        'Climb aboard a pleasure boat for a 1-hour cruise down the River Seine, before or after your 3-course-lunch including a drink at the Bistro Parisien on the quay near the Eiffel Tower. Take your seats in an entirely glassed-over boat, and enjoy panoramic views of the finest parts of Paris. Relax to the background music as you learn the history of Paris, from its medieval origins on the Ile de la Cité, to the secrets of some of its mansions. Glide past the golden dome of Les Invalides, see the elegant Musée d’Orsay, admire the palatial home of the Louvre Museum, pass the historic exhibition hall of the Grand Palais, and much more. Lunch is served from 11:00 to 15:00, meaning you are free to take it before or after your cruise. Enjoy views of the Eiffel Tower from the Bistro Parisien. The chef uses seasonal products to prepare tasty and authentic cuisine for your enjoyment.',
        48.860385,
        2.293565,
        'Dining',
        4.3,
        54.5,
        120,
        false,
        'http://www.partner.viator.com/en/13257/tours/Paris/Bateaux-Parisiens-Bistro-Parisien-lunch-sightseeing-cruise/d479-5836P2?eap=prod-sRa7AtLuF4UkLYO6mKPY-13257&aid=vba13257en',
        ARRAY['https://media.timeout.com/images/105347952/image.jpg'],
        'Paris',
        'France');
INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES ('Walk & Wine Tour in the Latin Quarter',
        'You will meet in the wine shop and tasting place called "Wine Tasting In Paris" offering the best wine experience in the city for more than 5 years. After a first glass of wine with the owner of the place, a French Sommelier, you will leave with your guide for 2 hours of walking in the charming small streets of Latin Quarter. You will see amazing places such as the Roman Arena, The food street of Rue Mouffetard, The Pantheon, The Sorbonne University. After the first glass of wine in the wine tasting place, you will have 3 more stops, In the small delicious cheese shop first where you will have a second glass of wine with a selection of French cheese, then you will stop in a hidden wine bar behind the Pantheon to taste some natural and organic wines, then you will have a last stop in a wine and finger food place which is perfect for a French aperitif. Here you will have your last glass and food included in the tour.... but of course you can stay there and have more drinks on your own!',
        48.8457939,
        2.3535812,
        'Tasting',
        4.9,
        84.56,
        120,
        false,
        'http://www.partner.viator.com/en/13257/tours/Paris/Walk-and-Wine-Tour-in-the-Latin-Quarter/d479-7815P6?eap=prod-lFcqmEVtIaXxELR2I9lo-13257&aid=vba13257en',
        ARRAY['https://shorelocalnews.com/wp-content/uploads/2023/05/judgment-of-paris-wine-tasting.jpg'],
        'Paris',
        'France');

INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES ('BMX lesson at EGP 18 skatepark, Paris 18th',
        'Paris BMX Club is a BMX school based in Paris which offers courses all year round, in the EGP 18 in the 18th district, all supervised by passionate and qualified instructors.Your BMX teacher will teach you the basics of this urban sport with a theoretical part and a warm-up beforehand, but above all a technical part to know how to learn and succeed the first figures in the skatepark or on the ground. <br />Overcome your fears, learn to fall and get up again, know your limits and go beyond them... These exercises will also help you in life because it is on self-confidence that everything is played!',
        48.899796,
        2.365714,
        'Sports/Lessons',
        3.5,
        40.0,
        60,
        false,
        'https://alentour.adrenaline-hunter.com/en-GB/embedded-booking/activity/9271?_cid=603',
        ARRAY['https://www.mellowboards.com/out/pictures/zmbwysiwygeditor/Blog-Posts/180222%20Project%204221%20in%20Paris/e-skate-paris.jpg'],
        'Paris',
        'France');
INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES ('Rollerblading lessons on the Place de la Bastille, Paris',
        'The Roller Club de France offers rollerblading lessons adapted to your level on the Place de la Bastille, in the heart of Paris.\n\nWhatever your level, beginner, intermediate or advanced, come and roller-skate with the Roller Club de France association. Classes are accessible to everyone! Do your children wish to learn or improve their skills in rollerblading? The Roller Club de France is made for them!',
        48.851704,
        2.367698,
        'Budget',
        4.0,
        20.0,
        60,
        false,
        'https://alentour.adrenaline-hunter.com/en-GB/embedded-booking/activity/4592?_cid=603',
        ARRAY['https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2017/05/1bc1a3802c11dafb9b83cd80c5182a5e.jpeg',
              'https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2017/05/b23d6c71f5335901291b4ac5fce8b535.jpeg',
              'https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2017/05/aac005789ee78f0dd1c068c2d245de03.jpeg',
              'https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2017/05/342a093e85b41ff38b50f7e7748012ae.jpeg',
              'https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2017/05/3eeba3844e6300b7d7bc81713ae1d29b.jpeg',
              'https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2017/05/761dacefacff00f0280112e2e8922ca0.jpeg',
              'https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2017/05/599a88d7b2707ece6713e3417e97f573.jpeg',
              'https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2017/05/c6aff1f4a6d0975205505989cd6e7717.jpeg'],
        'Paris',
        'France');

