INSERT INTO attractions(name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES
  ('Alhambra',
    'Visit the stunning palace and fortress complex.',
    37.1761,
    -3.5881,
    'Cultural',
    4.8,
    14,
    180,
    true,
    'https://www.viator.com/tours/Granada/Alhambra-Entrance-Ticket/d554-5550P48',
    '{"https://thetourguy.com/wp-content/uploads/2021/11/Alhambra-Fortress-Granada-Spain-700-x-425.jpg", "https://blogs-images.forbes.com/geoffreymorrison/files/2015/10/Alhambra-by-Geoffrey-Morrison-17.jpg", "https://ychef.files.bbci.co.uk/976x549/p05d1gkg.jpg"}',
    'Granada',
    'Spain'),

  ('Generalife',
    'Explore the beautiful gardens located near the Alhambra.',
    37.1745,
    -3.5928,
    'Cultural',
    4.7,
    7,
    120,
    false,
    'https://www.viator.com/tours/Granada/Generalife-Entrance-Ticket/d554-5550P49',
    '{"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/74/c9/40/caption.jpg?w=1200&h=1200&s=1"}',
    'Granada',
    'Spain'),

  ('Granada Cathedral',
    'Visit the grand Roman Catholic church in the city center.',
    37.1765,
    -3.5979,
    'Cultural',
    4.6,
    5,
    60,
    true,
    'https://www.viator.com/tours/Granada/Granada-Cathedral-Entrance-Ticket/d554-5550P50',
    '{"https://img.theculturetrip.com/wp-content/uploads/2017/04/5891086948_f47af831e0_b.jpg", "https://media.tacdn.com/media/attractions-splice-spp-674x446/06/70/0a/e6.jpg"}',
    'Granada',
    'Spain'),

  ('Royal Chapel of Granada',
    'Visit the Isabelline style chapel where the Catholic Monarchs are buried.',
    37.1765,
    -3.5982,
    'Cultural',
    4.5,
    5,
    60,
    false,
    'https://www.viator.com/tours/Granada/Royal-Chapel-of-Granada-Entrance-Ticket/d554-5550P51',
    '{"https://media.tacdn.com/media/attractions-splice-spp-674x446/06/70/0a/e8.jpg", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5o7t2VKcfywJCb4xcEZfRJYAEA7MB5PJtJ3crSnVqfPS6e9jovl7vKBuU6-RIUvt-wo8&usqp=CAU"}',
    'Granada',
    'Spain'),

  ('Albaicin',
    'Stroll through the traditional Arabic district known for its narrow winding streets.',
    37.1808,
    -3.5874,
    'Walking',
    4.6,
    0,
    120,
    false,
    'https://www.viator.com/tours/Granada/Albaicin-Walking-Tour/d554-5550P52',
    '{"https://www.alhambra.org/img/visitas/46.jpg", "https://go2alhambra.com/images/district-albaicin.jpg"}',
    'Granada',
    'Spain'),

  ('Sacromonte',
    'Visit the traditional neighborhood known for its cave houses.',
    37.1841,
    -3.5888,
    'Walking',
    4.4,
    0,
    120,
    false,
    'https://www.viator.com/tours/Granada/Sacromonte-Visit/d554-5550P53',
    '{"https://www.barcelo.com/guia-turismo/wp-content/uploads/2018/09/sacromonte-destacada.jpg"}',
    'Granada',
    'Spain'),

  ('Carrera del Darro',
    'Enjoy a walk along the scenic riverbank.',
    37.1768,
    -3.5902,
    'Walking',
    4.3,
    0,
    90,
    false,
    'https://www.viator.com/tours/Granada/Carrera-del-Darro-Walking-Tour/d554-5550P54',
    '{"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-ojA6e66e6kUxYEMYg8w0wydT_zkOnfcGDfUnkFz-XRhThV3gMjf29EIjThCr5gt5Q8s&usqp=CAU"}',
    'Granada',
    'Spain'),

  ('Palacio de Los Olvidados',
    'Visit the museum dedicated to Sephardic culture.',
    37.1784,
    -3.5941,
    'Cultural',
    4.1,
    5,
    60,
    false,
    'https://www.viator.com/tours/Granada/Palacio-de-Los-Olvidados-Entrance-Ticket/d554-5550P55',
    '{"https://cdn.getyourguide.com/img/tour/5d15f0471b94d.jpeg/146.jpg"}',
    'Granada',
    'Spain'),

  ('Basilica of San Juan de Dios',
    'Explore the stunning baroque church.',
    37.1749,
    -3.6043,
    'Cultural',
    4.7,
    5,
    60,
    true,
    'https://www.viator.com/tours/Granada/Basilica-of-San-Juan-de-Dios-Entrance-Ticket/d554-5550P56',
    '{"https://go2alhambra.com/images/granada-basilika.jpg", "https://mappingspain.com/wp-content/uploads/2020/10/Basilica-of-San-Juan-de-Dios-Granada-5-1024x683.jpg", "https://basilicasanjuandedios.es/wp-content/uploads/Camarin-y-Salas-San-Juan-de-Dios-15.jpg"}',
    'Granada',
    'Spain'),

  ('Carmen de los Martires',
    'Visit the beautiful 19th-century mansion and gardens.',
    37.1770,
    -3.5893,
    'Sightsee',
    4.6,
    0,
    90,
    false,
    'https://www.viator.com/tours/Granada/Carmen-de-los-Martires-Visit/d554-5550P57',
    '{"https://i0.wp.com/www.rulandomundo.com/wp-content/uploads/carmen-de-los-martires.jpg?fit=1024%2C769&ssl=1"}',
    'Granada',
    'Spain');

INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES 
('Mezquita Cathedral',
 'Marvel at the stunning architecture of the cathedral built inside a former mosque.',
 37.8789,
 -4.7794,
 'Cultural',
 4.8,
 11,
 120,
 true,
 'https://www.viator.com/tours/Cordoba/Mezquita-Cathedral-Entrance-Ticket/d5254-5550P38',
 '{"https://www.reviewofreligions.org/wp-content/uploads/2020/10/shutterstock_1450691789-1024x683.jpg", "https://mezquita-catedraldecordoba.es/site/assets/files/1038/home_cabecera2_2048x1536.jpg"}',
 'Cordoba',
 'Spain'),

('Alcazar de los Reyes Cristianos',
 'Explore the fortress ordered by King Alfonso XI of Castile.',
 37.8776,
 -4.7793,
 'Cultural',
 4.8,
 5,
 90,
 true,
 'https://www.viator.com/tours/Cordoba/Alcazar-de-los-Reyes-Cristianos-Entrance-Ticket/d5254-5550P39',
 '{"https://www.espanaguide.com/images/cordoba/alcazar/alcazar-de-los-reyes-cristianos-cordoba-mobile.jpg", "https://www.spain.info/export/sites/segtur/.content/imagenes/cabeceras-grandes/andalucia/alcazar-reyes-cordoba-s511384591.jpg_1014274486.jpg"}',
 'Cordoba',
 'Spain'),

('Roman Bridge',
 'Stroll along the historic bridge over the Guadalquivir.',
 37.8747,
 -4.7791,
 'Sightsee',
 4.7,
 0,
 30,
 true,
 'https://www.viator.com/tours/Cordoba/Roman-Bridge-Walking-Tour/d5254-5550P40',
 '{"https://www.historyhit.com/app/uploads/2020/11/Cordoba-Roman-Bridge_shutterstock.jpg", "https://farm66.staticflickr.com/65535/48906232242_fd4f191dbf_c.jpg", "https://thumbs.dreamstime.com/b/great-mosque-roman-bridge-cordoba-spain-guadalquivir-river-33940416.jpg"}',
 'Cordoba',
 'Spain'),

('Calahorra Tower',
 'Visit the fortified gate in the historic district of the city.',
 37.8741,
 -4.7794,
 'Sightsee',
 4.4,
 5,
 60,
 false,
 'https://www.viator.com/tours/Cordoba/Calahorra-Tower-Entrance-Ticket/d5254-5550P41',
 '{"https://www.spain.info/.content/imagenes/cabeceras-grandes/andalucia/torre-calahorra-cordoba-s1504876778.jpg"}',
 'Cordoba',
 'Spain'),

('Medina Azahara',
 'Explore the archaeological site of the city built by Abd-ar-Rahman III al-Nasir.',
 37.8847,
 -4.8678,
 'Cultural',
 4.6,
 9,
 180,
 false,
 'https://www.viator.com/tours/Cordoba/Medina-Azahara-Entrance-Ticket/d5254-5550P42',
 '{"https://www.cyclefiesta.com/images/articles/medina-azahara-850.jpg"}',
 'Cordoba',
 'Spain'),

('Palacio de Viana',
 'Visit the palace known for its 12 magnificent patios and a garden.',
 37.8876,
 -4.7791,
 'Cultural',
 4.6,
 8,
 120,
 false,
 'https://www.viator.com/tours/Cordoba/Palacio-de-Viana-Entrance-Ticket/d5254-5550P43',
 '{"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/2a/b1/64/palacio-museo-de-viana.jpg?w=1200&h=-1&s=1"}',
 'Cordoba',
 'Spain'),

('Cordoba Synagogue',
 'Explore the Jewish synagogue in the Jewish Quarter.',
 37.8815,
 -4.7811,
 'Cultural',
 4.1,
 4,
 60,
 false,
 'https://www.viator.com/tours/Cordoba/Cordoba-Synagogue-Entrance-Ticket/d5254-5550P44',
 '{"https://cdn.getyourguide.com/img/tour/9ee35146e63aa92d.jpeg/146.jpg"}',
 'Cordoba',
 'Spain'),

('Roman Temple',
 'Visit the remains of the Roman temple in the city center.',
 37.8844,
 -4.7811,
 'Cultural',
 4.2,
 0,
 30,
 false,
 'https://www.viator.com/tours/Cordoba/Roman-Temple-Visit/d5254-5550P45',
 '{"https://cdn.getyourguide.com/img/location/5729b43f52876.jpeg/68.jpg"}',
 'Cordoba',
 'Spain'),

('Julio Romero de Torres Museum',
 'Visit the museum dedicated to the works of the Spanish painter Julio Romero de Torres.',
 37.8792,
 -4.7792,
 'Cultural',
 4.4,
 4,
 90,
 false,
 'https://www.viator.com/tours/Cordoba/Julio-Romero-de-Torres-Museum-Entrance-Ticket/d5254-5550P46',
 '{"https://media-cdn.tripadvisor.com/media/photo-s/13/90/40/49/img-20180703-152419-largejpg.jpg"}',
 'Cordoba',
 'Spain'),

('Casa de Sefarad',
 'Explore the museum dedicated to Sephardic culture.',
 37.8814,
 -4.7792,
 'Cultural',
 4.6,
 4,
 60,
 false,
 'https://www.viator.com/tours/Cordoba/Casa-de-Sefarad-Entrance-Ticket/d5254-5550P47',
 '{"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/ed/74/1c/casa-de-sefarad.jpg?w=1200&h=-1&s=1"}',
 'Cordoba',
 'Spain');
