INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES ('South Bank (Available in Spanish)',
        'A long time ago when the West London area was evolving, the southern area, on the banks of the river, was a marshy area where only boats had access, today, thanks to the British exhibition festival in 1951 it is one of the areas chicest London with must-see places. Cross the famous and spectacular bridge of the towers to walk near the banks of the Thames observing its modern architecture, its impressive skyscrapers .. Enter the oldest and highest quality market in the country where we can find stalls with products from all over the world. Immerse yourself in the pirate history of pirates and corsairs, admiring an authentic pirate ship the Golden Hinde. Be in awe of London''s first Gothic Church, once a church of artists, writers and poets. The beautiful cathedral on the South bank Visit Shakespeare''s Globe, the theater where his first plays took place and which meant so much to him and his company. Enjoy panoramic views on this tour that ends in front of the impressive St Pauls Cathedral.\n\nFree tour: Book for free and pay what you want at the end',
        51.510118,
        -0.076661,
        'Walking Tour',
        4.4,
        0.0,
        120,
        false,
        'https://www.guruwalk.com/walks/28481-south-bank?ref=ojlgpuf3oo1nuk2s74m5',
        ARRAY['https://media.guruwalk.com/mt0ztqqq5tzl96db64s4b8nunn6u',
              'https://media.guruwalk.com/qdnoi44vz3pdkg7fe2tyhtb9794t',
              'https://media.guruwalk.com/0dai3wjh5s2jco6u00eak2hm6ok6',
              'https://media.guruwalk.com/uoq48eowwuzacoeqbe3rh5d63yov',
              'https://media.guruwalk.com/kud5owr7jg2nxcc07qfp7k7ggv60'],
        'London',
        'United Kingdom');

INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES ('Greenwich a fairytale place (Available in Spanish)',
        'Please book at least one day in advance as you need to make a reservation for the museum and you have to ensure that the group is full. Minimum 6 adults are needed for the tour to depart.<br><br> <strong>Try to arrive at least 10 minutes before the tour starts</strong> .<br><br> This is a free tour, that is to say free tour not free, where you value the quality of the visit. <strong><br><br>Keep in mind that you can pay in cash or card but euros or another currency that is not the pound are not accepted.</strong><br><br> Enter the colorful Royal Borough of Greenwich, famous for its maritime history and for being the location of the meridian, and above all for having been occupied by royalty for centuries.<br><br> We will begin by telling the story of the only surviving clipper in the world, the fastest of its time, Cutty Sark.<br><br> We will be amazed by the magnificent architecture of its university, we will discover all the uses it has had and what it was in the past.<br><br> We will walk through its splendid park and go up to the observatory to enjoy spectacular views and discover all the history, mysteries and curiosities of the Royal Observatory. Without failing to visit the Naval Museum.<br><br> We will visit one of the best markets in London, with a vibrant atmosphere and cobblestone floors. Book now and enjoy a unique experience in a fairytale place.<br><br><br></p><p>Free tour: Book for free and pay what you want at the end',
        51.4818,
        -0.010933,
        'Walking Tour',
        4.3,
        0.0,
        150,
        false,
        'https://www.guruwalk.com/walks/38798-greenwich-a-fairytale-place?ref=ojlgpuf3oo1nuk2s74m5',
        ARRAY['https://d1i21eq0w7p1n3.cloudfront.net/s5vto8s8dudvqia28dmv20m9xm0g',
              'https://d1i21eq0w7p1n3.cloudfront.net/6mvu3sma1dgr3gig800kmfn3hhpp',
              'https://d1i21eq0w7p1n3.cloudfront.net/dghtrb57fo9ahlkbhzwvod3keikx',
              'https://d1i21eq0w7p1n3.cloudfront.net/z92fqqw3wxz2jx5e0yuusqe1xskf',
              'https://d1i21eq0w7p1n3.cloudfront.net/a89dvjub4a215y8wafq3h86ne1hm'],
        'London',
        'United Kingdom');

INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES ('The Original Free Tour of London (Available in English)',
        'No other tour covers so many major London landmarks! Have your cameras at the ready as we walk past Westminster Abbey and the Big Ben, and see where the Queen and Prince Charles live as we stroll past Buckingham and St. James Palaces. On this 3-hour free walking tour you''ll tick off many of London''s must-see sites.Your London Free Tour starts in front of the Apple Store in Covent Garden and finishes by Westminster Abbey. Around every corner is another piece of royal history on this free London walking tour! Your guide will tell you about Winston Churchill as you walk past the Churchill War Rooms, talk about Guy Fawkes as you stroll past the Houses of Parliament, and tell you about Admiral Nelson as you visit the Nelson Column on Trafalgar Square. With other must-see sites like Covent Garden, Horse Guards Parade and of course, the Big Ben, this London gratuity-based free walking tour shows you many major landmarks.',
        51.512229,
        -0.123497,
        'Walking Tour',
        4.1,
        0.0,
        180,
        false,
        'https://www.guruwalk.com/walks/41199-the-original-free-tour-of-london?ref=ojlgpuf3oo1nuk2s74m5',
        ARRAY['https://media.guruwalk.com/mcqx32xi8wyym6awkfu5ilelq8gw',
              'https://media.guruwalk.com/68dsiqc45zucg2wmsimmv4de41dc',
              'https://media.guruwalk.com/dlkx4avr86dtqouztc32odwsiviq',
              'https://media.guruwalk.com/ubmgb6qqsbdi7jc0zgfc8293trf7',
              'https://media.guruwalk.com/02wm3bw5310od03nwlm9t8bjs9s6'],
        'London',
        'United Kingdom');

INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES ('History, betrayals and mystery in London (Available in Spanish)',
        'Do you want to move to London without leaving home? Join us on this Virtual Tour to discover an area of London full of history, mystery and anecdotes. We will start at the Roman wall and I will tell you why it was necessary to build it, how the Romans first arrived in London and what they did to occupy the territory. We will discover who was arriving after the most powerful Empire in the world, betrayals, battles, dynasties, etc. You will accompany us to the Tower of London fortress with the most history in the United Kingdom to discover all the uses it has had and what mysteries it houses. To finish I will tell you the anecdotes of one of the most emblematic and spectacular bridges in the world, the famous Tower Bridge. You do not miss the hype! Any questions or queries are welcome so go ahead!',
        51.509561,
        -0.07617,
        'Walking Tour',
        3.0,
        0.0,
        60,
        false,
        'https://www.guruwalk.com/walks/38629-history-betrayals-and-mystery-in-london?ref=ojlgpuf3oo1nuk2s74m5',
        ARRAY['https://media.guruwalk.com/2cg3sio54tsae4098ci0biq6mfay',
              'https://media.guruwalk.com/5pcfgz96lbfg1m3bfq0ylbmoaj17',
              'https://media.guruwalk.com/j2hu5vgohh6po3y7crzsj16itwlj',
              'https://media.guruwalk.com/v0k0ahm0cuuv2ki2dafxy67y8cd1',
              'https://media.guruwalk.com/dfzbqtn281mi8fhhjie4bkxmkeif'],
        'London',
        'United Kingdom');

INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES ('Scenic Stroll on the Southbank (Available in )',
        'The Southbank is the heart of London''s cultural scene, with opportunities to experience theatre, art, and literature. There are so many beautiful things about the history of this area that you will discover, once you take this tour. Learn more about the history of the Globe theatre, the best upcoming cultural events, and find hidden gems that you likely wouldn''t find by yourself. Intrigued? Then book my tour to find out more!',
        51.501343,
        -0.124841,
        'Walking Tour',
        4.4,
        0.0,
        105,
        false,
        'https://www.guruwalk.com/walks/38897-scenic-stroll-on-the-southbank?ref=ojlgpuf3oo1nuk2s74m5',
        ARRAY['https://d1i21eq0w7p1n3.cloudfront.net/395sm0hkdb1nwdruo26vbnxlekok',
              'https://d1i21eq0w7p1n3.cloudfront.net/ivqvjgwp7fre2k0qp8j2idvk4va3',
              'https://d1i21eq0w7p1n3.cloudfront.net/zdew4jymapptpq3cuzmhh7czbvcj',
              'https://d1i21eq0w7p1n3.cloudfront.net/6yero2f0ba23qdav4atjjcb380pe'],
        'London',
        'United Kingdom');

INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES ('Essential London Free Tour - Westminster (Available in Spanish)',
        'Walking around the most iconic places in central London is something that no visitor can miss, but most people stay above ground and miss out on many of the things that make this part of London so important. If you want to see familiar places like Trafalgar Square, Buckingham Palace, the Houses of Parliament or Westminster Abbey from a different point of view, this is the tour for you. From Covent Garden to Parliament Square via The Mall, St. Jame''s Park and much more, we won''t leave a corner unexplored as we enter the heart of London.',
        51.512214,
        -0.123568,
        'Walking Tour',
        4.1,
        0.0,
        150,
        false,
        'https://www.guruwalk.com/walks/38875-essential-london-free-tour-westminster?ref=ojlgpuf3oo1nuk2s74m5',
        ARRAY['https://d1i21eq0w7p1n3.cloudfront.net/glneuy10e2oroq9yvmy1jods002e',
              'https://d1i21eq0w7p1n3.cloudfront.net/blxtffbhsl18nqxahlfw3czkun89',
              'https://d1i21eq0w7p1n3.cloudfront.net/81wntk7fzikd8ocdc7vsdzpo7w9g',
              'https://d1i21eq0w7p1n3.cloudfront.net/idz7rgsrout1z7gpq12qqj0nu0v1',
              'https://d1i21eq0w7p1n3.cloudfront.net/iazl4svzv5szujzcbyrcidszznn4'],
        'London',
        'United Kingdom');

INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES ('Climbing experience on The O2 Arena in London',
        'Up at The O2 is a 90-minute experience you wont forget. Zip up your climb jacket. Pull-on your boots. Hook up your harness. Then make your way up the south face of one of the most striking buildings in Londons skyline. Leading the way will be one of our friendly climb guides. They know all sorts of interesting facts about The O2, from its unique architecture to its famous visitors. So feel free to ask questions as you climb. At the summit, youll be standing 52 meters above the legendary arena, with 360-degree views across this historic part of London beside the River Thames. Ready to experience something out of the ordinary?',
        51.503038,
        0.003154,
        'Sports/Action',
        4.0,
        42.49,
        90,
        false,
        'https://amadeus-discover.adrenaline-hunter.com/en-GB/embedded-booking/activity/7052?_cid=693',
        ARRAY['https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2022/03/a7059b20e236abdfb3a1fde82e67ed25.jpg',
              'https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2022/03/bf8525f7130667f54b55d99e0f0d8473.jpg',
              'https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2022/03/ccd28944b211e89f892ee6ada58d564b.jpg',
              'https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2022/03/3bd1439f9334c1cc1356d107affa7070.jpg',
              'https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2022/03/34991477cf1aa64a5deb8801be8bbfe6.jpg',
              'https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2022/03/fdddb68353e1286985590e313040da45.jpg',
              'https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2022/03/8795a8e9581638b0c7b572e4eb41723b.jpg',
              'https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2018/06/1a0875e336ecc4abffefbbad59259a22.jpeg',
              'https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2022/03/de82bc1d52129d2691a0c346e1297704.jpg',
              'https://media.manawa.com/cache/activity_gallery_zoom_770x500/media/2022/03/1027b673c8518bba07a80e19332982dd.jpg'],
        'London',
        'United Kingdom');

INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES ('Free Hidden London Tour (Available in English)',
        'Discover the best of hidden London on this unique free walking tour! One of the best free things to do in London, this free walking tour of London will introduce you to a side of London you haven’t seen before! Join this free walking tour of London and you’ll find London’s Oldest House, meet a Talking Cat and discover which of the famous London attractions is home to Secret Pineapples! You’ll also find Historic Golden Statues, Literary Pubs and hear one of London’s greatest love stories which still influences a global Wedding Tradition. Plus find out why Dragons are important to the city, which iconic London building Broke All The Rules of advertising and more! With all the best kept secrets of the City of London included, this free walking tour of London will introduce you to a whole new way of London sightseeing!',
        51.520219,
        -0.097677,
        'Walking Tour',
        4.2,
        0.0,
        150,
        false,
        'https://www.guruwalk.com/walks/39314-free-hidden-london-tour?ref=ojlgpuf3oo1nuk2s74m5',
        ARRAY['https://media.guruwalk.com/iydngder97zksdqmz4bmrotodqed',
              'https://media.guruwalk.com/xrgm6jb7qhkab9o92zcexkfwkgaq',
              'https://media.guruwalk.com/r3u20sne71ft6smhan1wt5c9420y',
              'https://media.guruwalk.com/zrk7ssweglcg1unajfd0tw3xg8ze',
              'https://media.guruwalk.com/9qgjy217ex5zx29b1br8hoogxplj'],
        'London',
        'United Kingdom');

INSERT INTO attractions (name, description, latitude, longitude, category, rating, price, duration, featured, booking_url, pictures, city, country)
VALUES ('Free Crime & Punishment Tour inc. Jack The Ripper! (Available in English)',
        'Bring the dark history of London to life on this sinister free walking tour! As the lights go down and darkness falls, this free walking tour will introduce you to the murky world of crime and punishment in London with gruesome true stories including Jack The Ripper where you will visit the last remaining site of his famous murders. Discover the truth behind London criminal history and visit the Criminal Court that is home to Deadmans Walk, all whilst finding the historic landmark which lays claim to being the oldest execution site in the city. Along the way, you will hear many of the most famous criminal stories as you relive the heist of the century at the Bank of England, recount the story of the Great Train Murder at Fenchurch Street and discover which historic crime inspired a classic Charles Dickens novel.',
        51.520219,
        -0.097677,
        'Walking Tour',
        4.2,
        0.0,
        180,
        false,
        'https://www.guruwalk.com/walks/39315-free-crime-punishment-tour-inc-jack-the-ripper?ref=ojlgpuf3oo1nuk2s74m5',
        ARRAY['https://static1.squarespace.com/static/6161bb5d58ee4e21599a0ec6/t/61d6eb459130b924a371a34f/1641474897516/IMG_86402c.jpg?format=1500w'],
        'London',
        'United Kingdom');
